export const ON_SET_IS_LOGIN = "ON_SET_IS_LOGIN";
export const SET_DATA_LIST = "SET_DATA_LIST";
export const SET_SELECTED_SEAT_DATA = "SET_SELECTED_SEAT_DATA";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_BOOKING_LIST = "SET_USER_BOOKING_LIST";

